---
- name: Revert cluster provisioning
  hosts: k3s_nodes
  become: true
  tasks:
    - name: Uninstall k3s
      import_role:
        name: k3s
        tasks_from: uninstall

    - name: Renable swap on fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^# (.*\sswap\s.*)$'
        line: '\1'
        backrefs: yes

    - name: Renable swap
      command: swapon -a
      ignore_errors: true  # can fail if has no swap partition/file configured

    - name: Uninstall monitoring stack
      import_role:
        name: monitoring
        tasks_from: uninstall
      ignore_errors: true
    
    - name: Uninstall GitOps
      import_role:
        name: gitops
        tasks_from: uninstall
      ignore_errors: true

    - name: Uninstall k3s
      import_role:
        name: k3s
        tasks_from: uninstall