apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: carneiro1908/app:sha-cb5c4822ad4f
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: DATABASE_URL
              value: postgresql://finance_user:finance_secure_password@db:5432/finance_dashboard