name: Deploy homelab infrastructure

on: 
  workflow_dispatch:


jobs:
  deploy_homelab_infrastructure:
    runs-on: self-hosted

    env:
      ANSIBLE_HOST: ${{ secrets.ANSIBLE_HOST }}
      ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Creates SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TARGET_VM_SSH_PRIVATE_KEY }}" > ~/.ssh/homelab_k8s
          chmod 600 ~/.ssh/homelab_k8s
        
      - name: Test SSH connection
        run: |
          ssh -vvv \
            -i ~/.ssh/homelab_k8s \
            -o StrictHostKeyChecking=no \
            $ANSIBLE_USER@$ANSIBLE_HOST "echo SSH OK"

      - name: Play ansible play-books
        run: |
          cd homelab-infra
          ANSIBLE_HOST="${ANSIBLE_HOST}" ansible-playbook -vvv playbooks/site.yml

      - name:  Check k3s nodes
        run: |
          sleep 120
          export KUBECONFIG=~/homelab-infra/kubeconfig/homelab.yaml

          sed -i 's/127.0.0.1/${ env.ANSIBLE_HOST }/' kubeconfig/homelab.yaml
          
          kubectl get nodes